### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by Rabosa616** [ERNI-Academy/assets-cloud-storage-abstraction#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running the sample app an exception is thrown when connecting to the container.
Looks like the development container is not defined on the project.

### Expected Behavior

Run the sample app without any exception

### Steps To Reproduce

- Navigate to the sample folder
- Load the sample app on visual studio
- Build the application
- Run the application

### Exceptions (if any)

Unhandled exception. System.AggregateException: One or more errors occurred. (Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)))

**Comment by mdelgadodiaz83-erni** [comment]
this issue is fixed with a warning on documentation. in order to works fine , the sample need the storage emulator installed.
